from __future__ import annotations

from enum import Enum


class errorCode(Enum):
    DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED"
    DB_TIMEOUT = "DB_TIMEOUT"
    DB_INTEGRITY = "DB_INTEGRITY"
    CACHE_UNAVAILABLE = "CACHE_UNAVAILABLE"
    CACHE_KEY_ERROR = "CACHE_KEY_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    RATE_LIMITED = "RATE_LIMITED"
    BLACKLISTED = "BLACKLISTED"
    CSRF_INVALID = "CSRF_INVALID"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"
